jasypt:
  encryptor:
    password: fleet
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fleet-test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: ENC(ZPuwhwfeVTiCHBXqX3tRRgfetivI/wtYAgiBday2VOkK50ixRVnwSHxPyrLLXNLr)
