server:
  port: 8001
spring:
  application:
    name: zookeeper-provider
  profiles:
    active: dev
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
        register: true
