spring:
  # 配置数据源
  datasource:
    order:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fleet-order?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password:
    goods:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fleet-goods?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password:
    user:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fleet-user?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password:
mybatis:
  mapper-locations: mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
