server:
  port: 8002
spring:
  application:
    name: seata-user
  profiles:
    active: dev
seata:
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  tx-service-group: my_test_tx_group
