spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: provider
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
          filters:
            # 去除掉前面一个前缀
            - StripPrefix=1
# 加载所有的端点，默认只加载了info、health
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    # 可以关闭指定的端点
    shutdown:
      enabled: false
info:
  blog-url: www.fleetsoft.com.cn
  author: fleet
  version: 1.0
  app:
    name: gateway
    port: 8000
