server:
  port: 8000
motan:
  # 注册中心配置
  registry:
    regProtocol: zookeeper
    address: localhost:2181
  # 协议配置
  protocol:
    name: motan
  #指 定需要解析的包名
  annotation:
    package: com.fleet
  # 客户端配置
  client:
    protocol: motan
    group: fleet
    check: false
    registry: registryConfig
