spring:
  redis:
    # redis数据库索引（默认为0）
    database: 0
    # redis服务器地址
    host: localhost
    # redis服务器连接端口
    port: 6379
    # redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
