server:
  port: 8000
spring:
  application:
    name: service-zuul
  profiles:
    active: dev
zuul:
  routes:
    service-provider:
      service-id: service-provider
      path: /provider/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
