/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.records;


import com.fleet.jooq.generator.tables.CheckContent;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckContentRecord extends UpdatableRecordImpl<CheckContentRecord> implements Record6<Integer, Integer, Integer, String, String, Integer> {

    private static final long serialVersionUID = -403562045;

    /**
     * Setter for <code>fleet-test.check_content.check_content_id</code>.
     */
    public void setCheckContentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fleet-test.check_content.check_content_id</code>.
     */
    public Integer getCheckContentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fleet-test.check_content.index</code>.
     */
    public void setIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fleet-test.check_content.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fleet-test.check_content.check_item_id</code>.
     */
    public void setCheckItemId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fleet-test.check_content.check_item_id</code>.
     */
    public Integer getCheckItemId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fleet-test.check_content.check_content</code>.
     */
    public void setCheckContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fleet-test.check_content.check_content</code>.
     */
    public String getCheckContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fleet-test.check_content.check_standard</code>.
     */
    public void setCheckStandard(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fleet-test.check_content.check_standard</code>.
     */
    public String getCheckStandard() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fleet-test.check_content.standard_score</code>.
     */
    public void setStandardScore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fleet-test.check_content.standard_score</code>.
     */
    public Integer getStandardScore() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CheckContent.CHECK_CONTENT.CHECK_CONTENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CheckContent.CHECK_CONTENT.INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CheckContent.CHECK_CONTENT.CHECK_ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CheckContent.CHECK_CONTENT.CHECK_CONTENT_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CheckContent.CHECK_CONTENT.CHECK_STANDARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return CheckContent.CHECK_CONTENT.STANDARD_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCheckContentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCheckItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCheckContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCheckStandard();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStandardScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCheckContentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCheckItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCheckContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCheckStandard();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStandardScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckContentRecord value1(Integer value) {
        setCheckContentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckContentRecord value2(Integer value) {
        setIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckContentRecord value3(Integer value) {
        setCheckItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckContentRecord value4(String value) {
        setCheckContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckContentRecord value5(String value) {
        setCheckStandard(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckContentRecord value6(Integer value) {
        setStandardScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckContentRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CheckContentRecord
     */
    public CheckContentRecord() {
        super(CheckContent.CHECK_CONTENT);
    }

    /**
     * Create a detached, initialised CheckContentRecord
     */
    public CheckContentRecord(Integer checkContentId, Integer index, Integer checkItemId, String checkContent, String checkStandard, Integer standardScore) {
        super(CheckContent.CHECK_CONTENT);

        set(0, checkContentId);
        set(1, index);
        set(2, checkItemId);
        set(3, checkContent);
        set(4, checkStandard);
        set(5, standardScore);
    }
}
