/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.records;


import com.fleet.jooq.generator.tables.Log;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 系统日志
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogRecord extends UpdatableRecordImpl<LogRecord> implements Record17<Long, UInteger, String, Integer, String, String, String, String, String, String, String, String, String, UInteger, String, Long, LocalDateTime> {

    private static final long serialVersionUID = 1988086286;

    /**
     * Setter for <code>fleet-test.log.id</code>. 日志id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fleet-test.log.id</code>. 日志id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fleet-test.log.user_id</code>. 操作用户id
     */
    public void setUserId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>fleet-test.log.user_id</code>. 操作用户id
     */
    public UInteger getUserId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>fleet-test.log.name</code>. 操作用户名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fleet-test.log.name</code>. 操作用户名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fleet-test.log.type</code>. 日志类型（1：用户登录，2：用户操作，3：用户登出）
     */
    public void setType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fleet-test.log.type</code>. 日志类型（1：用户登录，2：用户操作，3：用户登出）
     */
    public Integer getType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fleet-test.log.log</code>. log信息
     */
    public void setLog(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fleet-test.log.log</code>. log信息
     */
    public String getLog() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fleet-test.log.url</code>. 网址
     */
    public void setUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fleet-test.log.url</code>. 网址
     */
    public String getUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fleet-test.log.http_method</code>. 请求方式
     */
    public void setHttpMethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fleet-test.log.http_method</code>. 请求方式
     */
    public String getHttpMethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fleet-test.log.method</code>. 方法名
     */
    public void setMethod(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fleet-test.log.method</code>. 方法名
     */
    public String getMethod() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fleet-test.log.params</code>. 参数
     */
    public void setParams(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fleet-test.log.params</code>. 参数
     */
    public String getParams() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fleet-test.log.ip</code>. IP地址
     */
    public void setIp(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>fleet-test.log.ip</code>. IP地址
     */
    public String getIp() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fleet-test.log.agent</code>. User-Agent
     */
    public void setAgent(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fleet-test.log.agent</code>. User-Agent
     */
    public String getAgent() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fleet-test.log.os</code>. 系统
     */
    public void setOs(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fleet-test.log.os</code>. 系统
     */
    public String getOs() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fleet-test.log.browser</code>. 浏览器
     */
    public void setBrowser(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fleet-test.log.browser</code>. 浏览器
     */
    public String getBrowser() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fleet-test.log.state</code>. 任务状态 （1：成功，0：失败）
     */
    public void setState(UInteger value) {
        set(13, value);
    }

    /**
     * Getter for <code>fleet-test.log.state</code>. 任务状态 （1：成功，0：失败）
     */
    public UInteger getState() {
        return (UInteger) get(13);
    }

    /**
     * Setter for <code>fleet-test.log.error</code>. 错误信息
     */
    public void setError(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fleet-test.log.error</code>. 错误信息
     */
    public String getError() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fleet-test.log.millis</code>. 执行时间（单位：毫秒）
     */
    public void setMillis(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>fleet-test.log.millis</code>. 执行时间（单位：毫秒）
     */
    public Long getMillis() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>fleet-test.log.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>fleet-test.log.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, UInteger, String, Integer, String, String, String, String, String, String, String, String, String, UInteger, String, Long, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, UInteger, String, Integer, String, String, String, String, String, String, String, String, String, UInteger, String, Long, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Log.LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Log.LOG.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Log.LOG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Log.LOG.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Log.LOG.LOG_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Log.LOG.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Log.LOG.HTTP_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Log.LOG.METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Log.LOG.PARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Log.LOG.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Log.LOG.AGENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Log.LOG.OS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Log.LOG.BROWSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field14() {
        return Log.LOG.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Log.LOG.ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return Log.LOG.MILLIS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field17() {
        return Log.LOG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getHttpMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getParams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAgent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getOs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getBrowser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component14() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getMillis();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getHttpMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getParams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAgent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getOs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getBrowser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value14() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getMillis();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value2(UInteger value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value4(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value5(String value) {
        setLog(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value6(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value7(String value) {
        setHttpMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value8(String value) {
        setMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value9(String value) {
        setParams(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value10(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value11(String value) {
        setAgent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value12(String value) {
        setOs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value13(String value) {
        setBrowser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value14(UInteger value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value15(String value) {
        setError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value16(Long value) {
        setMillis(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord value17(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LogRecord values(Long value1, UInteger value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, UInteger value14, String value15, Long value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LogRecord
     */
    public LogRecord() {
        super(Log.LOG);
    }

    /**
     * Create a detached, initialised LogRecord
     */
    public LogRecord(Long id, UInteger userId, String name, Integer type, String log, String url, String httpMethod, String method, String params, String ip, String agent, String os, String browser, UInteger state, String error, Long millis, LocalDateTime createTime) {
        super(Log.LOG);

        set(0, id);
        set(1, userId);
        set(2, name);
        set(3, type);
        set(4, log);
        set(5, url);
        set(6, httpMethod);
        set(7, method);
        set(8, params);
        set(9, ip);
        set(10, agent);
        set(11, os);
        set(12, browser);
        set(13, state);
        set(14, error);
        set(15, millis);
        set(16, createTime);
    }
}
