/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.records;


import com.fleet.jooq.generator.tables.Msg;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 角色
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MsgRecord extends UpdatableRecordImpl<MsgRecord> implements Record8<UInteger, String, String, String, UInteger, UInteger, LocalDateTime, UInteger> {

    private static final long serialVersionUID = 2144467481;

    /**
     * Setter for <code>fleet-test.msg.id</code>. 消息id
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>fleet-test.msg.id</code>. 消息id
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>fleet-test.msg.title</code>. 消息标题
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fleet-test.msg.title</code>. 消息标题
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fleet-test.msg.excerpt</code>. 消息摘要
     */
    public void setExcerpt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fleet-test.msg.excerpt</code>. 消息摘要
     */
    public String getExcerpt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fleet-test.msg.url</code>. 网址
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fleet-test.msg.url</code>. 网址
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fleet-test.msg.state</code>. 消息状态（0：未发布，1：已发布）
     */
    public void setState(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>fleet-test.msg.state</code>. 消息状态（0：未发布，1：已发布）
     */
    public UInteger getState() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>fleet-test.msg.creator_id</code>. 创建人
     */
    public void setCreatorId(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>fleet-test.msg.creator_id</code>. 创建人
     */
    public UInteger getCreatorId() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>fleet-test.msg.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>fleet-test.msg.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>fleet-test.msg.deleted</code>. 是否删除（1：是，0：否）
     */
    public void setDeleted(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>fleet-test.msg.deleted</code>. 是否删除（1：是，0：否）
     */
    public UInteger getDeleted() {
        return (UInteger) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, String, String, String, UInteger, UInteger, LocalDateTime, UInteger> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, String, String, String, UInteger, UInteger, LocalDateTime, UInteger> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Msg.MSG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Msg.MSG.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Msg.MSG.EXCERPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Msg.MSG.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return Msg.MSG.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return Msg.MSG.CREATOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Msg.MSG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return Msg.MSG.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExcerpt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component6() {
        return getCreatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component8() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExcerpt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getCreatorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value3(String value) {
        setExcerpt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value5(UInteger value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value6(UInteger value) {
        setCreatorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord value8(UInteger value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MsgRecord values(UInteger value1, String value2, String value3, String value4, UInteger value5, UInteger value6, LocalDateTime value7, UInteger value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MsgRecord
     */
    public MsgRecord() {
        super(Msg.MSG);
    }

    /**
     * Create a detached, initialised MsgRecord
     */
    public MsgRecord(UInteger id, String title, String excerpt, String url, UInteger state, UInteger creatorId, LocalDateTime createTime, UInteger deleted) {
        super(Msg.MSG);

        set(0, id);
        set(1, title);
        set(2, excerpt);
        set(3, url);
        set(4, state);
        set(5, creatorId);
        set(6, createTime);
        set(7, deleted);
    }
}
