/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.records;


import com.fleet.jooq.generator.tables.QuartzJob;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuartzJobRecord extends UpdatableRecordImpl<QuartzJobRecord> implements Record9<UInteger, String, String, String, String, String, UInteger, String, UInteger> {

    private static final long serialVersionUID = -444206375;

    /**
     * Setter for <code>fleet-test.quartz_job.id</code>. 定时器id
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.id</code>. 定时器id
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.job_name</code>. 定时器名称
     */
    public void setJobName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.job_name</code>. 定时器名称
     */
    public String getJobName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.bean_name</code>. Bean名称
     */
    public void setBeanName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.bean_name</code>. Bean名称
     */
    public String getBeanName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.method_name</code>. 方法名称
     */
    public void setMethodName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.method_name</code>. 方法名称
     */
    public String getMethodName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.param</code>. 参数
     */
    public void setParam(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.param</code>. 参数
     */
    public String getParam() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.cron_expression</code>. cron表达式
     */
    public void setCronExpression(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.cron_expression</code>. cron表达式
     */
    public String getCronExpression() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.enabled</code>. 是否启用（1：是，0：否）
     */
    public void setEnabled(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.enabled</code>. 是否启用（1：是，0：否）
     */
    public UInteger getEnabled() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fleet-test.quartz_job.deleted</code>. 是否删除（1：是，0：否）
     */
    public void setDeleted(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>fleet-test.quartz_job.deleted</code>. 是否删除（1：是，0：否）
     */
    public UInteger getDeleted() {
        return (UInteger) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, String, String, String, String, String, UInteger, String, UInteger> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, String, String, String, String, String, UInteger, String, UInteger> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return QuartzJob.QUARTZ_JOB.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QuartzJob.QUARTZ_JOB.JOB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return QuartzJob.QUARTZ_JOB.BEAN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return QuartzJob.QUARTZ_JOB.METHOD_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return QuartzJob.QUARTZ_JOB.PARAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return QuartzJob.QUARTZ_JOB.CRON_EXPRESSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return QuartzJob.QUARTZ_JOB.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return QuartzJob.QUARTZ_JOB.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field9() {
        return QuartzJob.QUARTZ_JOB.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBeanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMethodName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getParam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCronExpression();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component9() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBeanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMethodName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getParam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCronExpression();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value9() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value2(String value) {
        setJobName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value3(String value) {
        setBeanName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value4(String value) {
        setMethodName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value5(String value) {
        setParam(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value6(String value) {
        setCronExpression(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value7(UInteger value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord value9(UInteger value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuartzJobRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, UInteger value7, String value8, UInteger value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuartzJobRecord
     */
    public QuartzJobRecord() {
        super(QuartzJob.QUARTZ_JOB);
    }

    /**
     * Create a detached, initialised QuartzJobRecord
     */
    public QuartzJobRecord(UInteger id, String jobName, String beanName, String methodName, String param, String cronExpression, UInteger enabled, String remark, UInteger deleted) {
        super(QuartzJob.QUARTZ_JOB);

        set(0, id);
        set(1, jobName);
        set(2, beanName);
        set(3, methodName);
        set(4, param);
        set(5, cronExpression);
        set(6, enabled);
        set(7, remark);
        set(8, deleted);
    }
}
