/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.CheckContent;
import com.fleet.jooq.generator.tables.records.CheckContentRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckContentDao extends DAOImpl<CheckContentRecord, com.fleet.jooq.generator.tables.pojos.CheckContent, Integer> {

    /**
     * Create a new CheckContentDao without any configuration
     */
    public CheckContentDao() {
        super(CheckContent.CHECK_CONTENT, com.fleet.jooq.generator.tables.pojos.CheckContent.class);
    }

    /**
     * Create a new CheckContentDao with an attached configuration
     */
    public CheckContentDao(Configuration configuration) {
        super(CheckContent.CHECK_CONTENT, com.fleet.jooq.generator.tables.pojos.CheckContent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.fleet.jooq.generator.tables.pojos.CheckContent object) {
        return object.getCheckContentId();
    }

    /**
     * Fetch records that have <code>check_content_id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.CheckContent> fetchByCheckContentId(Integer... values) {
        return fetch(CheckContent.CHECK_CONTENT.CHECK_CONTENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>check_content_id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.CheckContent fetchOneByCheckContentId(Integer value) {
        return fetchOne(CheckContent.CHECK_CONTENT.CHECK_CONTENT_ID, value);
    }

    /**
     * Fetch records that have <code>index IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.CheckContent> fetchByIndex(Integer... values) {
        return fetch(CheckContent.CHECK_CONTENT.INDEX, values);
    }

    /**
     * Fetch records that have <code>check_item_id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.CheckContent> fetchByCheckItemId(Integer... values) {
        return fetch(CheckContent.CHECK_CONTENT.CHECK_ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>check_content IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.CheckContent> fetchByCheckContent(String... values) {
        return fetch(CheckContent.CHECK_CONTENT.CHECK_CONTENT_, values);
    }

    /**
     * Fetch records that have <code>check_standard IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.CheckContent> fetchByCheckStandard(String... values) {
        return fetch(CheckContent.CHECK_CONTENT.CHECK_STANDARD, values);
    }

    /**
     * Fetch records that have <code>standard_score IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.CheckContent> fetchByStandardScore(Integer... values) {
        return fetch(CheckContent.CHECK_CONTENT.STANDARD_SCORE, values);
    }
}
