/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.Content;
import com.fleet.jooq.generator.tables.records.ContentRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentDao extends DAOImpl<ContentRecord, com.fleet.jooq.generator.tables.pojos.Content, Integer> {

    /**
     * Create a new ContentDao without any configuration
     */
    public ContentDao() {
        super(Content.CONTENT, com.fleet.jooq.generator.tables.pojos.Content.class);
    }

    /**
     * Create a new ContentDao with an attached configuration
     */
    public ContentDao(Configuration configuration) {
        super(Content.CONTENT, com.fleet.jooq.generator.tables.pojos.Content.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.fleet.jooq.generator.tables.pojos.Content object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Content> fetchById(Integer... values) {
        return fetch(Content.CONTENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.Content fetchOneById(Integer value) {
        return fetchOne(Content.CONTENT.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Content> fetchByTitle(String... values) {
        return fetch(Content.CONTENT.TITLE, values);
    }

    /**
     * Fetch records that have <code>desc IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Content> fetchByDesc(String... values) {
        return fetch(Content.CONTENT.DESC, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Content> fetchByUrl(String... values) {
        return fetch(Content.CONTENT.URL, values);
    }
}
