/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.Dict;
import com.fleet.jooq.generator.tables.records.DictRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictDao extends DAOImpl<DictRecord, com.fleet.jooq.generator.tables.pojos.Dict, UInteger> {

    /**
     * Create a new DictDao without any configuration
     */
    public DictDao() {
        super(Dict.DICT, com.fleet.jooq.generator.tables.pojos.Dict.class);
    }

    /**
     * Create a new DictDao with an attached configuration
     */
    public DictDao(Configuration configuration) {
        super(Dict.DICT, com.fleet.jooq.generator.tables.pojos.Dict.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.Dict object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Dict> fetchById(UInteger... values) {
        return fetch(Dict.DICT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.Dict fetchOneById(UInteger value) {
        return fetchOne(Dict.DICT.ID, value);
    }

    /**
     * Fetch records that have <code>group IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Dict> fetchByGroup(String... values) {
        return fetch(Dict.DICT.GROUP, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Dict> fetchByRemark(String... values) {
        return fetch(Dict.DICT.REMARK, values);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Dict> fetchByDeleted(UInteger... values) {
        return fetch(Dict.DICT.DELETED, values);
    }
}
