/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.Log;
import com.fleet.jooq.generator.tables.records.LogRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * 系统日志
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogDao extends DAOImpl<LogRecord, com.fleet.jooq.generator.tables.pojos.Log, Long> {

    /**
     * Create a new LogDao without any configuration
     */
    public LogDao() {
        super(Log.LOG, com.fleet.jooq.generator.tables.pojos.Log.class);
    }

    /**
     * Create a new LogDao with an attached configuration
     */
    public LogDao(Configuration configuration) {
        super(Log.LOG, com.fleet.jooq.generator.tables.pojos.Log.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.fleet.jooq.generator.tables.pojos.Log object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchById(Long... values) {
        return fetch(Log.LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.Log fetchOneById(Long value) {
        return fetchOne(Log.LOG.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByUserId(UInteger... values) {
        return fetch(Log.LOG.USER_ID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByName(String... values) {
        return fetch(Log.LOG.NAME, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByType(Integer... values) {
        return fetch(Log.LOG.TYPE, values);
    }

    /**
     * Fetch records that have <code>log IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByLog(String... values) {
        return fetch(Log.LOG.LOG_, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByUrl(String... values) {
        return fetch(Log.LOG.URL, values);
    }

    /**
     * Fetch records that have <code>http_method IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByHttpMethod(String... values) {
        return fetch(Log.LOG.HTTP_METHOD, values);
    }

    /**
     * Fetch records that have <code>method IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByMethod(String... values) {
        return fetch(Log.LOG.METHOD, values);
    }

    /**
     * Fetch records that have <code>params IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByParams(String... values) {
        return fetch(Log.LOG.PARAMS, values);
    }

    /**
     * Fetch records that have <code>ip IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByIp(String... values) {
        return fetch(Log.LOG.IP, values);
    }

    /**
     * Fetch records that have <code>agent IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByAgent(String... values) {
        return fetch(Log.LOG.AGENT, values);
    }

    /**
     * Fetch records that have <code>os IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByOs(String... values) {
        return fetch(Log.LOG.OS, values);
    }

    /**
     * Fetch records that have <code>browser IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByBrowser(String... values) {
        return fetch(Log.LOG.BROWSER, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByState(UInteger... values) {
        return fetch(Log.LOG.STATE, values);
    }

    /**
     * Fetch records that have <code>error IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByError(String... values) {
        return fetch(Log.LOG.ERROR, values);
    }

    /**
     * Fetch records that have <code>millis IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByMillis(Long... values) {
        return fetch(Log.LOG.MILLIS, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Log> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Log.LOG.CREATE_TIME, values);
    }
}
