/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.MailGroup;
import com.fleet.jooq.generator.tables.records.MailGroupRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * 邮箱组信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailGroupDao extends DAOImpl<MailGroupRecord, com.fleet.jooq.generator.tables.pojos.MailGroup, UInteger> {

    /**
     * Create a new MailGroupDao without any configuration
     */
    public MailGroupDao() {
        super(MailGroup.MAIL_GROUP, com.fleet.jooq.generator.tables.pojos.MailGroup.class);
    }

    /**
     * Create a new MailGroupDao with an attached configuration
     */
    public MailGroupDao(Configuration configuration) {
        super(MailGroup.MAIL_GROUP, com.fleet.jooq.generator.tables.pojos.MailGroup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.MailGroup object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.MailGroup> fetchById(UInteger... values) {
        return fetch(MailGroup.MAIL_GROUP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.MailGroup fetchOneById(UInteger value) {
        return fetchOne(MailGroup.MAIL_GROUP.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.MailGroup> fetchByName(String... values) {
        return fetch(MailGroup.MAIL_GROUP.NAME, values);
    }

    /**
     * Fetch records that have <code>tos IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.MailGroup> fetchByTos(String... values) {
        return fetch(MailGroup.MAIL_GROUP.TOS, values);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.MailGroup> fetchByDeleted(UInteger... values) {
        return fetch(MailGroup.MAIL_GROUP.DELETED, values);
    }
}
