/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.Permission;
import com.fleet.jooq.generator.tables.records.PermissionRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * 权限管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionDao extends DAOImpl<PermissionRecord, com.fleet.jooq.generator.tables.pojos.Permission, UInteger> {

    /**
     * Create a new PermissionDao without any configuration
     */
    public PermissionDao() {
        super(Permission.PERMISSION, com.fleet.jooq.generator.tables.pojos.Permission.class);
    }

    /**
     * Create a new PermissionDao with an attached configuration
     */
    public PermissionDao(Configuration configuration) {
        super(Permission.PERMISSION, com.fleet.jooq.generator.tables.pojos.Permission.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.Permission object) {
        return object.getPermissionId();
    }

    /**
     * Fetch records that have <code>permission_id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Permission> fetchByPermissionId(UInteger... values) {
        return fetch(Permission.PERMISSION.PERMISSION_ID, values);
    }

    /**
     * Fetch a unique record that has <code>permission_id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.Permission fetchOneByPermissionId(UInteger value) {
        return fetchOne(Permission.PERMISSION.PERMISSION_ID, value);
    }

    /**
     * Fetch records that have <code>permission_name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Permission> fetchByPermissionName(String... values) {
        return fetch(Permission.PERMISSION.PERMISSION_NAME, values);
    }

    /**
     * Fetch records that have <code>permission_code IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Permission> fetchByPermissionCode(String... values) {
        return fetch(Permission.PERMISSION.PERMISSION_CODE, values);
    }

    /**
     * Fetch records that have <code>permission_order IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Permission> fetchByPermissionOrder(UInteger... values) {
        return fetch(Permission.PERMISSION.PERMISSION_ORDER, values);
    }

    /**
     * Fetch records that have <code>upper_permission_id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Permission> fetchByUpperPermissionId(UInteger... values) {
        return fetch(Permission.PERMISSION.UPPER_PERMISSION_ID, values);
    }
}
