/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.QuartzJob;
import com.fleet.jooq.generator.tables.records.QuartzJobRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuartzJobDao extends DAOImpl<QuartzJobRecord, com.fleet.jooq.generator.tables.pojos.QuartzJob, UInteger> {

    /**
     * Create a new QuartzJobDao without any configuration
     */
    public QuartzJobDao() {
        super(QuartzJob.QUARTZ_JOB, com.fleet.jooq.generator.tables.pojos.QuartzJob.class);
    }

    /**
     * Create a new QuartzJobDao with an attached configuration
     */
    public QuartzJobDao(Configuration configuration) {
        super(QuartzJob.QUARTZ_JOB, com.fleet.jooq.generator.tables.pojos.QuartzJob.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.QuartzJob object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchById(UInteger... values) {
        return fetch(QuartzJob.QUARTZ_JOB.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.QuartzJob fetchOneById(UInteger value) {
        return fetchOne(QuartzJob.QUARTZ_JOB.ID, value);
    }

    /**
     * Fetch records that have <code>job_name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByJobName(String... values) {
        return fetch(QuartzJob.QUARTZ_JOB.JOB_NAME, values);
    }

    /**
     * Fetch records that have <code>bean_name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByBeanName(String... values) {
        return fetch(QuartzJob.QUARTZ_JOB.BEAN_NAME, values);
    }

    /**
     * Fetch records that have <code>method_name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByMethodName(String... values) {
        return fetch(QuartzJob.QUARTZ_JOB.METHOD_NAME, values);
    }

    /**
     * Fetch records that have <code>param IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByParam(String... values) {
        return fetch(QuartzJob.QUARTZ_JOB.PARAM, values);
    }

    /**
     * Fetch records that have <code>cron_expression IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByCronExpression(String... values) {
        return fetch(QuartzJob.QUARTZ_JOB.CRON_EXPRESSION, values);
    }

    /**
     * Fetch records that have <code>enabled IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByEnabled(UInteger... values) {
        return fetch(QuartzJob.QUARTZ_JOB.ENABLED, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByRemark(String... values) {
        return fetch(QuartzJob.QUARTZ_JOB.REMARK, values);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.QuartzJob> fetchByDeleted(UInteger... values) {
        return fetch(QuartzJob.QUARTZ_JOB.DELETED, values);
    }
}
