/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.UserCopy;
import com.fleet.jooq.generator.tables.records.UserCopyRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * 用户信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCopyDao extends DAOImpl<UserCopyRecord, com.fleet.jooq.generator.tables.pojos.UserCopy, UInteger> {

    /**
     * Create a new UserCopyDao without any configuration
     */
    public UserCopyDao() {
        super(UserCopy.USER_COPY, com.fleet.jooq.generator.tables.pojos.UserCopy.class);
    }

    /**
     * Create a new UserCopyDao with an attached configuration
     */
    public UserCopyDao(Configuration configuration) {
        super(UserCopy.USER_COPY, com.fleet.jooq.generator.tables.pojos.UserCopy.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.UserCopy object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.UserCopy> fetchById(UInteger... values) {
        return fetch(UserCopy.USER_COPY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.UserCopy fetchOneById(UInteger value) {
        return fetchOne(UserCopy.USER_COPY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.UserCopy> fetchByName(String... values) {
        return fetch(UserCopy.USER_COPY.NAME, values);
    }
}
