/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.UserCopy1;
import com.fleet.jooq.generator.tables.records.UserCopy1Record;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCopy1Dao extends DAOImpl<UserCopy1Record, com.fleet.jooq.generator.tables.pojos.UserCopy1, UInteger> {

    /**
     * Create a new UserCopy1Dao without any configuration
     */
    public UserCopy1Dao() {
        super(UserCopy1.USER_COPY1, com.fleet.jooq.generator.tables.pojos.UserCopy1.class);
    }

    /**
     * Create a new UserCopy1Dao with an attached configuration
     */
    public UserCopy1Dao(Configuration configuration) {
        super(UserCopy1.USER_COPY1, com.fleet.jooq.generator.tables.pojos.UserCopy1.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.UserCopy1 object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.UserCopy1> fetchById(UInteger... values) {
        return fetch(UserCopy1.USER_COPY1.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.UserCopy1 fetchOneById(UInteger value) {
        return fetchOne(UserCopy1.USER_COPY1.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.UserCopy1> fetchByName(String... values) {
        return fetch(UserCopy1.USER_COPY1.NAME, values);
    }
}
