/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.UserCopy1Copy;
import com.fleet.jooq.generator.tables.records.UserCopy1CopyRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCopy1CopyDao extends DAOImpl<UserCopy1CopyRecord, com.fleet.jooq.generator.tables.pojos.UserCopy1Copy, UInteger> {

    /**
     * Create a new UserCopy1CopyDao without any configuration
     */
    public UserCopy1CopyDao() {
        super(UserCopy1Copy.USER_COPY1_COPY, com.fleet.jooq.generator.tables.pojos.UserCopy1Copy.class);
    }

    /**
     * Create a new UserCopy1CopyDao with an attached configuration
     */
    public UserCopy1CopyDao(Configuration configuration) {
        super(UserCopy1Copy.USER_COPY1_COPY, com.fleet.jooq.generator.tables.pojos.UserCopy1Copy.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.UserCopy1Copy object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.UserCopy1Copy> fetchById(UInteger... values) {
        return fetch(UserCopy1Copy.USER_COPY1_COPY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.UserCopy1Copy fetchOneById(UInteger value) {
        return fetchOne(UserCopy1Copy.USER_COPY1_COPY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.UserCopy1Copy> fetchByName(String... values) {
        return fetch(UserCopy1Copy.USER_COPY1_COPY.NAME, values);
    }
}
