/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.daos;


import com.fleet.jooq.generator.tables.Value;
import com.fleet.jooq.generator.tables.records.ValueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDao extends DAOImpl<ValueRecord, com.fleet.jooq.generator.tables.pojos.Value, UInteger> {

    /**
     * Create a new ValueDao without any configuration
     */
    public ValueDao() {
        super(Value.VALUE, com.fleet.jooq.generator.tables.pojos.Value.class);
    }

    /**
     * Create a new ValueDao with an attached configuration
     */
    public ValueDao(Configuration configuration) {
        super(Value.VALUE, com.fleet.jooq.generator.tables.pojos.Value.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected UInteger getId(com.fleet.jooq.generator.tables.pojos.Value object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchById(UInteger... values) {
        return fetch(Value.VALUE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.fleet.jooq.generator.tables.pojos.Value fetchOneById(UInteger value) {
        return fetchOne(Value.VALUE.ID, value);
    }

    /**
     * Fetch records that have <code>dict_id IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchByDictId(UInteger... values) {
        return fetch(Value.VALUE.DICT_ID, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchByCode(String... values) {
        return fetch(Value.VALUE.CODE, values);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchByValue(String... values) {
        return fetch(Value.VALUE.VALUE_, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchByRemark(String... values) {
        return fetch(Value.VALUE.REMARK, values);
    }

    /**
     * Fetch records that have <code>sort IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchBySort(UInteger... values) {
        return fetch(Value.VALUE.SORT, values);
    }

    /**
     * Fetch records that have <code>is_default IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchByIsDefault(UInteger... values) {
        return fetch(Value.VALUE.IS_DEFAULT, values);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.fleet.jooq.generator.tables.pojos.Value> fetchByDeleted(UInteger... values) {
        return fetch(Value.VALUE.DELETED, values);
    }
}
