/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator;


import com.fleet.jooq.generator.tables.Author;
import com.fleet.jooq.generator.tables.Book;
import com.fleet.jooq.generator.tables.CheckContent;
import com.fleet.jooq.generator.tables.CheckItem;
import com.fleet.jooq.generator.tables.Content;
import com.fleet.jooq.generator.tables.Dept;
import com.fleet.jooq.generator.tables.DeptCopy;
import com.fleet.jooq.generator.tables.Dict;
import com.fleet.jooq.generator.tables.Job;
import com.fleet.jooq.generator.tables.Log;
import com.fleet.jooq.generator.tables.MailGroup;
import com.fleet.jooq.generator.tables.Menu;
import com.fleet.jooq.generator.tables.MenuCopy;
import com.fleet.jooq.generator.tables.Money;
import com.fleet.jooq.generator.tables.Msg;
import com.fleet.jooq.generator.tables.OauthClientDetails;
import com.fleet.jooq.generator.tables.PdtItem;
import com.fleet.jooq.generator.tables.Permission;
import com.fleet.jooq.generator.tables.QuartzJob;
import com.fleet.jooq.generator.tables.QuartzJobLog;
import com.fleet.jooq.generator.tables.Recommendsps;
import com.fleet.jooq.generator.tables.Role;
import com.fleet.jooq.generator.tables.RoleMenu;
import com.fleet.jooq.generator.tables.To;
import com.fleet.jooq.generator.tables.User;
import com.fleet.jooq.generator.tables.UserCopy;
import com.fleet.jooq.generator.tables.UserCopy1;
import com.fleet.jooq.generator.tables.UserCopy1Copy;
import com.fleet.jooq.generator.tables.UserCopyCopy;
import com.fleet.jooq.generator.tables.UserDept;
import com.fleet.jooq.generator.tables.UserRole;
import com.fleet.jooq.generator.tables.Value;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>fleet-test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHOR_PRIMARY = Indexes0.AUTHOR_PRIMARY;
    public static final Index BOOK_PRIMARY = Indexes0.BOOK_PRIMARY;
    public static final Index CHECK_CONTENT_PRIMARY = Indexes0.CHECK_CONTENT_PRIMARY;
    public static final Index CHECK_ITEM_PRIMARY = Indexes0.CHECK_ITEM_PRIMARY;
    public static final Index CONTENT_PRIMARY = Indexes0.CONTENT_PRIMARY;
    public static final Index DEPT_PRIMARY = Indexes0.DEPT_PRIMARY;
    public static final Index DEPT_COPY_PRIMARY = Indexes0.DEPT_COPY_PRIMARY;
    public static final Index DICT_PRIMARY = Indexes0.DICT_PRIMARY;
    public static final Index JOB_PRIMARY = Indexes0.JOB_PRIMARY;
    public static final Index LOG_PRIMARY = Indexes0.LOG_PRIMARY;
    public static final Index MAIL_GROUP_PRIMARY = Indexes0.MAIL_GROUP_PRIMARY;
    public static final Index MENU_PRIMARY = Indexes0.MENU_PRIMARY;
    public static final Index MENU_COPY_PRIMARY = Indexes0.MENU_COPY_PRIMARY;
    public static final Index MONEY_UNI_ = Indexes0.MONEY_UNI_;
    public static final Index MSG_PRIMARY = Indexes0.MSG_PRIMARY;
    public static final Index OAUTH_CLIENT_DETAILS_PRIMARY = Indexes0.OAUTH_CLIENT_DETAILS_PRIMARY;
    public static final Index PDT_ITEM_PRIMARY = Indexes0.PDT_ITEM_PRIMARY;
    public static final Index PERMISSION_PRIMARY = Indexes0.PERMISSION_PRIMARY;
    public static final Index QUARTZ_JOB_PRIMARY = Indexes0.QUARTZ_JOB_PRIMARY;
    public static final Index QUARTZ_JOB_LOG_PRIMARY = Indexes0.QUARTZ_JOB_LOG_PRIMARY;
    public static final Index RECOMMENDSPS_PRIMARY = Indexes0.RECOMMENDSPS_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index ROLE_MENU_PRIMARY = Indexes0.ROLE_MENU_PRIMARY;
    public static final Index ROLE_MENU_UNI_ROLE_MENU = Indexes0.ROLE_MENU_UNI_ROLE_MENU;
    public static final Index TO_PRIMARY = Indexes0.TO_PRIMARY;
    public static final Index TO_UNI_USER_MSG = Indexes0.TO_UNI_USER_MSG;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_COPY_PRIMARY = Indexes0.USER_COPY_PRIMARY;
    public static final Index USER_COPY1_PRIMARY = Indexes0.USER_COPY1_PRIMARY;
    public static final Index USER_COPY1_COPY_PRIMARY = Indexes0.USER_COPY1_COPY_PRIMARY;
    public static final Index USER_COPY1_COPY_UNI_ID = Indexes0.USER_COPY1_COPY_UNI_ID;
    public static final Index USER_COPY_COPY_PRIMARY = Indexes0.USER_COPY_COPY_PRIMARY;
    public static final Index USER_COPY_COPY_UNI_NAME = Indexes0.USER_COPY_COPY_UNI_NAME;
    public static final Index USER_DEPT_UNI_USER_ROLE = Indexes0.USER_DEPT_UNI_USER_ROLE;
    public static final Index USER_ROLE_UNI_USER_ROLE = Indexes0.USER_ROLE_UNI_USER_ROLE;
    public static final Index VALUE_PRIMARY = Indexes0.VALUE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHOR_PRIMARY = Internal.createIndex("PRIMARY", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index BOOK_PRIMARY = Internal.createIndex("PRIMARY", Book.BOOK, new OrderField[] { Book.BOOK.ID }, true);
        public static Index CHECK_CONTENT_PRIMARY = Internal.createIndex("PRIMARY", CheckContent.CHECK_CONTENT, new OrderField[] { CheckContent.CHECK_CONTENT.CHECK_CONTENT_ID }, true);
        public static Index CHECK_ITEM_PRIMARY = Internal.createIndex("PRIMARY", CheckItem.CHECK_ITEM, new OrderField[] { CheckItem.CHECK_ITEM.CHECK_ITEM_ID }, true);
        public static Index CONTENT_PRIMARY = Internal.createIndex("PRIMARY", Content.CONTENT, new OrderField[] { Content.CONTENT.ID }, true);
        public static Index DEPT_PRIMARY = Internal.createIndex("PRIMARY", Dept.DEPT, new OrderField[] { Dept.DEPT.ID }, true);
        public static Index DEPT_COPY_PRIMARY = Internal.createIndex("PRIMARY", DeptCopy.DEPT_COPY, new OrderField[] { DeptCopy.DEPT_COPY.ID }, true);
        public static Index DICT_PRIMARY = Internal.createIndex("PRIMARY", Dict.DICT, new OrderField[] { Dict.DICT.ID }, true);
        public static Index JOB_PRIMARY = Internal.createIndex("PRIMARY", Job.JOB, new OrderField[] { Job.JOB.JOB_ID }, true);
        public static Index LOG_PRIMARY = Internal.createIndex("PRIMARY", Log.LOG, new OrderField[] { Log.LOG.ID }, true);
        public static Index MAIL_GROUP_PRIMARY = Internal.createIndex("PRIMARY", MailGroup.MAIL_GROUP, new OrderField[] { MailGroup.MAIL_GROUP.ID }, true);
        public static Index MENU_PRIMARY = Internal.createIndex("PRIMARY", Menu.MENU, new OrderField[] { Menu.MENU.MENU_ID }, true);
        public static Index MENU_COPY_PRIMARY = Internal.createIndex("PRIMARY", MenuCopy.MENU_COPY, new OrderField[] { MenuCopy.MENU_COPY.ID }, true);
        public static Index MONEY_UNI_ = Internal.createIndex("uni_", Money.MONEY, new OrderField[] { Money.MONEY.NAME }, true);
        public static Index MSG_PRIMARY = Internal.createIndex("PRIMARY", Msg.MSG, new OrderField[] { Msg.MSG.ID }, true);
        public static Index OAUTH_CLIENT_DETAILS_PRIMARY = Internal.createIndex("PRIMARY", OauthClientDetails.OAUTH_CLIENT_DETAILS, new OrderField[] { OauthClientDetails.OAUTH_CLIENT_DETAILS.CLIENT_ID }, true);
        public static Index PDT_ITEM_PRIMARY = Internal.createIndex("PRIMARY", PdtItem.PDT_ITEM, new OrderField[] { PdtItem.PDT_ITEM.PDT_ITEM_ID }, true);
        public static Index PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", Permission.PERMISSION, new OrderField[] { Permission.PERMISSION.PERMISSION_ID }, true);
        public static Index QUARTZ_JOB_PRIMARY = Internal.createIndex("PRIMARY", QuartzJob.QUARTZ_JOB, new OrderField[] { QuartzJob.QUARTZ_JOB.ID }, true);
        public static Index QUARTZ_JOB_LOG_PRIMARY = Internal.createIndex("PRIMARY", QuartzJobLog.QUARTZ_JOB_LOG, new OrderField[] { QuartzJobLog.QUARTZ_JOB_LOG.JOB_LOG_ID }, true);
        public static Index RECOMMENDSPS_PRIMARY = Internal.createIndex("PRIMARY", Recommendsps.RECOMMENDSPS, new OrderField[] { Recommendsps.RECOMMENDSPS.ID }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index ROLE_MENU_PRIMARY = Internal.createIndex("PRIMARY", RoleMenu.ROLE_MENU, new OrderField[] { RoleMenu.ROLE_MENU.ID }, true);
        public static Index ROLE_MENU_UNI_ROLE_MENU = Internal.createIndex("uni_role_menu", RoleMenu.ROLE_MENU, new OrderField[] { RoleMenu.ROLE_MENU.ROLE_ID, RoleMenu.ROLE_MENU.MENU_ID }, true);
        public static Index TO_PRIMARY = Internal.createIndex("PRIMARY", To.TO, new OrderField[] { To.TO.ID }, true);
        public static Index TO_UNI_USER_MSG = Internal.createIndex("uni_user_msg", To.TO, new OrderField[] { To.TO.ID, To.TO.TO_ }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_COPY_PRIMARY = Internal.createIndex("PRIMARY", UserCopy.USER_COPY, new OrderField[] { UserCopy.USER_COPY.ID }, true);
        public static Index USER_COPY1_PRIMARY = Internal.createIndex("PRIMARY", UserCopy1.USER_COPY1, new OrderField[] { UserCopy1.USER_COPY1.ID }, true);
        public static Index USER_COPY1_COPY_PRIMARY = Internal.createIndex("PRIMARY", UserCopy1Copy.USER_COPY1_COPY, new OrderField[] { UserCopy1Copy.USER_COPY1_COPY.ID }, true);
        public static Index USER_COPY1_COPY_UNI_ID = Internal.createIndex("uni_id", UserCopy1Copy.USER_COPY1_COPY, new OrderField[] { UserCopy1Copy.USER_COPY1_COPY.ID }, true);
        public static Index USER_COPY_COPY_PRIMARY = Internal.createIndex("PRIMARY", UserCopyCopy.USER_COPY_COPY, new OrderField[] { UserCopyCopy.USER_COPY_COPY.ID }, true);
        public static Index USER_COPY_COPY_UNI_NAME = Internal.createIndex("uni_name", UserCopyCopy.USER_COPY_COPY, new OrderField[] { UserCopyCopy.USER_COPY_COPY.NAME }, true);
        public static Index USER_DEPT_UNI_USER_ROLE = Internal.createIndex("uni_user_role", UserDept.USER_DEPT, new OrderField[] { UserDept.USER_DEPT.USER_ID, UserDept.USER_DEPT.DEPT_ID }, true);
        public static Index USER_ROLE_UNI_USER_ROLE = Internal.createIndex("uni_user_role", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE_ID }, true);
        public static Index VALUE_PRIMARY = Internal.createIndex("PRIMARY", Value.VALUE, new OrderField[] { Value.VALUE.ID }, true);
    }
}
