/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckItem implements Serializable {

    private static final long serialVersionUID = -324524680;

    private Integer checkItemId;
    private Integer index;
    private String  checkType;
    private String  type;
    private String  checkItem;
    private Integer ratio;

    public CheckItem() {}

    public CheckItem(CheckItem value) {
        this.checkItemId = value.checkItemId;
        this.index = value.index;
        this.checkType = value.checkType;
        this.type = value.type;
        this.checkItem = value.checkItem;
        this.ratio = value.ratio;
    }

    public CheckItem(
        Integer checkItemId,
        Integer index,
        String  checkType,
        String  type,
        String  checkItem,
        Integer ratio
    ) {
        this.checkItemId = checkItemId;
        this.index = index;
        this.checkType = checkType;
        this.type = type;
        this.checkItem = checkItem;
        this.ratio = ratio;
    }

    public Integer getCheckItemId() {
        return this.checkItemId;
    }

    public void setCheckItemId(Integer checkItemId) {
        this.checkItemId = checkItemId;
    }

    public Integer getIndex() {
        return this.index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getCheckType() {
        return this.checkType;
    }

    public void setCheckType(String checkType) {
        this.checkType = checkType;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCheckItem() {
        return this.checkItem;
    }

    public void setCheckItem(String checkItem) {
        this.checkItem = checkItem;
    }

    public Integer getRatio() {
        return this.ratio;
    }

    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CheckItem (");

        sb.append(checkItemId);
        sb.append(", ").append(index);
        sb.append(", ").append(checkType);
        sb.append(", ").append(type);
        sb.append(", ").append(checkItem);
        sb.append(", ").append(ratio);

        sb.append(")");
        return sb.toString();
    }
}
