/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckContent implements Serializable {

    private static final long serialVersionUID = -297571581;

    private Integer checkContentId;
    private Integer index;
    private Integer checkItemId;
    private String  checkContent;
    private String  checkStandard;
    private Integer standardScore;

    public CheckContent() {}

    public CheckContent(CheckContent value) {
        this.checkContentId = value.checkContentId;
        this.index = value.index;
        this.checkItemId = value.checkItemId;
        this.checkContent = value.checkContent;
        this.checkStandard = value.checkStandard;
        this.standardScore = value.standardScore;
    }

    public CheckContent(
        Integer checkContentId,
        Integer index,
        Integer checkItemId,
        String  checkContent,
        String  checkStandard,
        Integer standardScore
    ) {
        this.checkContentId = checkContentId;
        this.index = index;
        this.checkItemId = checkItemId;
        this.checkContent = checkContent;
        this.checkStandard = checkStandard;
        this.standardScore = standardScore;
    }

    public Integer getCheckContentId() {
        return this.checkContentId;
    }

    public void setCheckContentId(Integer checkContentId) {
        this.checkContentId = checkContentId;
    }

    public Integer getIndex() {
        return this.index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public Integer getCheckItemId() {
        return this.checkItemId;
    }

    public void setCheckItemId(Integer checkItemId) {
        this.checkItemId = checkItemId;
    }

    public String getCheckContent() {
        return this.checkContent;
    }

    public void setCheckContent(String checkContent) {
        this.checkContent = checkContent;
    }

    public String getCheckStandard() {
        return this.checkStandard;
    }

    public void setCheckStandard(String checkStandard) {
        this.checkStandard = checkStandard;
    }

    public Integer getStandardScore() {
        return this.standardScore;
    }

    public void setStandardScore(Integer standardScore) {
        this.standardScore = standardScore;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CheckContent (");

        sb.append(checkContentId);
        sb.append(", ").append(index);
        sb.append(", ").append(checkItemId);
        sb.append(", ").append(checkContent);
        sb.append(", ").append(checkStandard);
        sb.append(", ").append(standardScore);

        sb.append(")");
        return sb.toString();
    }
}
