/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Content implements Serializable {

    private static final long serialVersionUID = 1297061461;

    private Integer id;
    private String  title;
    private String  desc;
    private String  url;

    public Content() {}

    public Content(Content value) {
        this.id = value.id;
        this.title = value.title;
        this.desc = value.desc;
        this.url = value.url;
    }

    public Content(
        Integer id,
        String  title,
        String  desc,
        String  url
    ) {
        this.id = id;
        this.title = title;
        this.desc = desc;
        this.url = url;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Content (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(desc);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
