/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dict implements Serializable {

    private static final long serialVersionUID = 48194088;

    private UInteger id;
    private String   group;
    private String   remark;
    private UInteger deleted;

    public Dict() {}

    public Dict(Dict value) {
        this.id = value.id;
        this.group = value.group;
        this.remark = value.remark;
        this.deleted = value.deleted;
    }

    public Dict(
        UInteger id,
        String   group,
        String   remark,
        UInteger deleted
    ) {
        this.id = id;
        this.group = group;
        this.remark = remark;
        this.deleted = deleted;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getGroup() {
        return this.group;
    }

    public void setGroup(String group) {
        this.group = group;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public UInteger getDeleted() {
        return this.deleted;
    }

    public void setDeleted(UInteger deleted) {
        this.deleted = deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Dict (");

        sb.append(id);
        sb.append(", ").append(group);
        sb.append(", ").append(remark);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
