/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * 邮箱组信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailGroup implements Serializable {

    private static final long serialVersionUID = -1537810990;

    private UInteger id;
    private String   name;
    private String   tos;
    private UInteger deleted;

    public MailGroup() {}

    public MailGroup(MailGroup value) {
        this.id = value.id;
        this.name = value.name;
        this.tos = value.tos;
        this.deleted = value.deleted;
    }

    public MailGroup(
        UInteger id,
        String   name,
        String   tos,
        UInteger deleted
    ) {
        this.id = id;
        this.name = name;
        this.tos = tos;
        this.deleted = deleted;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTos() {
        return this.tos;
    }

    public void setTos(String tos) {
        this.tos = tos;
    }

    public UInteger getDeleted() {
        return this.deleted;
    }

    public void setDeleted(UInteger deleted) {
        this.deleted = deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MailGroup (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(tos);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
