/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Money implements Serializable {

    private static final long serialVersionUID = -774859237;

    private String  name;
    private Integer money;

    public Money() {}

    public Money(Money value) {
        this.name = value.name;
        this.money = value.money;
    }

    public Money(
        String  name,
        Integer money
    ) {
        this.name = name;
        this.money = money;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getMoney() {
        return this.money;
    }

    public void setMoney(Integer money) {
        this.money = money;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Money (");

        sb.append(name);
        sb.append(", ").append(money);

        sb.append(")");
        return sb.toString();
    }
}
