/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PdtItem implements Serializable {

    private static final long serialVersionUID = 1925670420;

    private Integer pdtItemId;
    private Integer index;
    private String  role;

    public PdtItem() {}

    public PdtItem(PdtItem value) {
        this.pdtItemId = value.pdtItemId;
        this.index = value.index;
        this.role = value.role;
    }

    public PdtItem(
        Integer pdtItemId,
        Integer index,
        String  role
    ) {
        this.pdtItemId = pdtItemId;
        this.index = index;
        this.role = role;
    }

    public Integer getPdtItemId() {
        return this.pdtItemId;
    }

    public void setPdtItemId(Integer pdtItemId) {
        this.pdtItemId = pdtItemId;
    }

    public Integer getIndex() {
        return this.index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PdtItem (");

        sb.append(pdtItemId);
        sb.append(", ").append(index);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
