/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuartzJobLog implements Serializable {

    private static final long serialVersionUID = -924859408;

    private UInteger      jobLogId;
    private UInteger      jobId;
    private String        jobName;
    private String        beanName;
    private String        methodName;
    private String        param;
    private String        cronExpression;
    private Integer       state;
    private String        error;
    private Long          millis;
    private LocalDateTime createTime;

    public QuartzJobLog() {}

    public QuartzJobLog(QuartzJobLog value) {
        this.jobLogId = value.jobLogId;
        this.jobId = value.jobId;
        this.jobName = value.jobName;
        this.beanName = value.beanName;
        this.methodName = value.methodName;
        this.param = value.param;
        this.cronExpression = value.cronExpression;
        this.state = value.state;
        this.error = value.error;
        this.millis = value.millis;
        this.createTime = value.createTime;
    }

    public QuartzJobLog(
        UInteger      jobLogId,
        UInteger      jobId,
        String        jobName,
        String        beanName,
        String        methodName,
        String        param,
        String        cronExpression,
        Integer       state,
        String        error,
        Long          millis,
        LocalDateTime createTime
    ) {
        this.jobLogId = jobLogId;
        this.jobId = jobId;
        this.jobName = jobName;
        this.beanName = beanName;
        this.methodName = methodName;
        this.param = param;
        this.cronExpression = cronExpression;
        this.state = state;
        this.error = error;
        this.millis = millis;
        this.createTime = createTime;
    }

    public UInteger getJobLogId() {
        return this.jobLogId;
    }

    public void setJobLogId(UInteger jobLogId) {
        this.jobLogId = jobLogId;
    }

    public UInteger getJobId() {
        return this.jobId;
    }

    public void setJobId(UInteger jobId) {
        this.jobId = jobId;
    }

    public String getJobName() {
        return this.jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public String getBeanName() {
        return this.beanName;
    }

    public void setBeanName(String beanName) {
        this.beanName = beanName;
    }

    public String getMethodName() {
        return this.methodName;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public String getParam() {
        return this.param;
    }

    public void setParam(String param) {
        this.param = param;
    }

    public String getCronExpression() {
        return this.cronExpression;
    }

    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getError() {
        return this.error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public Long getMillis() {
        return this.millis;
    }

    public void setMillis(Long millis) {
        this.millis = millis;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuartzJobLog (");

        sb.append(jobLogId);
        sb.append(", ").append(jobId);
        sb.append(", ").append(jobName);
        sb.append(", ").append(beanName);
        sb.append(", ").append(methodName);
        sb.append(", ").append(param);
        sb.append(", ").append(cronExpression);
        sb.append(", ").append(state);
        sb.append(", ").append(error);
        sb.append(", ").append(millis);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
