/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Recommendsps implements Serializable {

    private static final long serialVersionUID = 1572692740;

    private Integer id;
    private String  initiator;
    private String  taskname;
    private String  definitionkey;
    private String  sps;
    private String  spsname;
    private String  spsassignes;
    private String  variable;

    public Recommendsps() {}

    public Recommendsps(Recommendsps value) {
        this.id = value.id;
        this.initiator = value.initiator;
        this.taskname = value.taskname;
        this.definitionkey = value.definitionkey;
        this.sps = value.sps;
        this.spsname = value.spsname;
        this.spsassignes = value.spsassignes;
        this.variable = value.variable;
    }

    public Recommendsps(
        Integer id,
        String  initiator,
        String  taskname,
        String  definitionkey,
        String  sps,
        String  spsname,
        String  spsassignes,
        String  variable
    ) {
        this.id = id;
        this.initiator = initiator;
        this.taskname = taskname;
        this.definitionkey = definitionkey;
        this.sps = sps;
        this.spsname = spsname;
        this.spsassignes = spsassignes;
        this.variable = variable;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getInitiator() {
        return this.initiator;
    }

    public void setInitiator(String initiator) {
        this.initiator = initiator;
    }

    public String getTaskname() {
        return this.taskname;
    }

    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    public String getDefinitionkey() {
        return this.definitionkey;
    }

    public void setDefinitionkey(String definitionkey) {
        this.definitionkey = definitionkey;
    }

    public String getSps() {
        return this.sps;
    }

    public void setSps(String sps) {
        this.sps = sps;
    }

    public String getSpsname() {
        return this.spsname;
    }

    public void setSpsname(String spsname) {
        this.spsname = spsname;
    }

    public String getSpsassignes() {
        return this.spsassignes;
    }

    public void setSpsassignes(String spsassignes) {
        this.spsassignes = spsassignes;
    }

    public String getVariable() {
        return this.variable;
    }

    public void setVariable(String variable) {
        this.variable = variable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Recommendsps (");

        sb.append(id);
        sb.append(", ").append(initiator);
        sb.append(", ").append(taskname);
        sb.append(", ").append(definitionkey);
        sb.append(", ").append(sps);
        sb.append(", ").append(spsname);
        sb.append(", ").append(spsassignes);
        sb.append(", ").append(variable);

        sb.append(")");
        return sb.toString();
    }
}
