/*
 * This file is generated by jOOQ.
 */
package com.fleet.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * 用户与角色对应关系
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleMenu implements Serializable {

    private static final long serialVersionUID = 412930895;

    private UInteger id;
    private UInteger roleId;
    private UInteger menuId;
    private UInteger deleted;

    public RoleMenu() {}

    public RoleMenu(RoleMenu value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.menuId = value.menuId;
        this.deleted = value.deleted;
    }

    public RoleMenu(
        UInteger id,
        UInteger roleId,
        UInteger menuId,
        UInteger deleted
    ) {
        this.id = id;
        this.roleId = roleId;
        this.menuId = menuId;
        this.deleted = deleted;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UInteger getRoleId() {
        return this.roleId;
    }

    public void setRoleId(UInteger roleId) {
        this.roleId = roleId;
    }

    public UInteger getMenuId() {
        return this.menuId;
    }

    public void setMenuId(UInteger menuId) {
        this.menuId = menuId;
    }

    public UInteger getDeleted() {
        return this.deleted;
    }

    public void setDeleted(UInteger deleted) {
        this.deleted = deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoleMenu (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(menuId);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
