// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.fleet.grpc.common;

public interface BooleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BooleanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool bool = 1;</code>
   * @return The bool.
   */
  boolean getBool();
}
