spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fleet-magic-api?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password:
magic-api:
  web: /magic/web
  resource:
    # 接口存储方式，file、database、redis
    type: database
    # 数据库中的表名
    table-name: magic_api_file
    # key 前缀
    prefix: /magic-api
    # 是否是只读模式
    readonly: false
  # 启用驼峰命名转换
  sql-column-case: camel
  # 分页配置
  page-config:
    # 页大小的请求参数名称
    size: size
    # 页码的请求参数名称
    page: page
    # 未传页码时的默认页码
    default-page: 1
    # 未传页大小时的默认页大小
    default-size: 10
