logging:
  level:
    com.fleet.caffeine.dao: debug
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fleet-test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password:
  cache:
    # 配置缓存，初始缓存容量为10，最大容量为500，过期时间为60秒
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=10,maximumSize=500,expireAfterAccess=60s
mybatis:
  mapper-locations: mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
