server:
  port: 8000
spring:
  application:
    name: service-ribbon
  profiles:
    active: dev
ribbon:
  eureka:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

